### ISSUE TITLE
Adding contributor roles to the metadata

### ISSUE THREAD

**Issue by dhimmel** [data2health/contributorship#5]
@nicolevasilevsky  wrote:

> Add something here about using CRO? Manubot should be be able to track our contributions in the yaml file too?

Yes, we can put extra fields for authors in `metadata.yaml`. For example we could do:

```yaml
  - github: nicolevasilevsky
    name: Nicole Vasilevsky
    initials: NV
    orcid: 0000-0001-5208-3432
    twitter: n_vasilevsky
    email: vasilevs@ohsu.edu
    affiliations:
      - Oregon Clinical and Translational Reseearch Institute, Oregon Health & Science University
      - Department of Medical Informatics and Clinical Epidemiology, Oregon Health & Science University
    roles:
      - CREDIT_00000013 writing original draft role
```

Currently we don't do anything with that information, but we could. @nicolevasilevsky should we show the roles in the manuscript?

**Comment by nicolevasilevsky** [comment]
I like the idea of showing the roles in the manuscript, thanks for doing that!

cc @kristiholmes

**Comment by nicolevasilevsky** [comment]
I will add the roles to the yaml file

**Comment by dhimmel** [comment]
Okay I'll touch base with our frontend dev @vincerubinetti on what might be some nice ways to display these roles in the manuscript frontmatter.

**Comment by nicolevasilevsky** [comment]
awesome, thanks!

**Comment by kristiholmes** [comment]
Agree - this is awesome! Thanks!

**Comment by jcolomb** [comment]
Please have a look at : https://jats4r.org/credit-taxonomy:
it would be best to define exactly what is under the role, url seem prefered to the PID ?

We should all discuss how to include CRO information.

**Comment by mellybelly** [comment]
@jcolomb the credit-taxonomy was incorporated into CRO; we were part of the original workshops that defined the taxonomy. CRO is a computational representation and a much more extensive set of concepts, however the original credit taxonomy can still be used as a subset.

**Comment by jcolomb** [comment]
the question is how to implement the CRO vocabulary into the paper metadata, see the link: there is a recommendation when using credit, but not for CRO.

**Comment by jcolomb** [comment]
An additional thought: any way to add contributors who are not authors something like:

```
- github: nicolevasilevsky
    name: Nicole Vasilevsky
    initials: NV
    orcid: 0000-0001-5208-3432
    twitter: n_vasilevsky
    email: vasilevs@ohsu.edu
    affiliations:
      - Oregon Clinical and Translational Reseearch Institute, Oregon Health & Science University
      - Department of Medical Informatics and Clinical Epidemiology, Oregon Health & Science University
    roles:
      - CREDIT_00000013 writing original draft role
    is_author: yes
    is_corresponding_author: no
```

(PS: I moved question about contributor role in #8)

**Comment by dhimmel** [comment]
> any way to add contributors who are not authors something like

Do you want the translators to show up on the manuscript, like we did for translators at https://greenelab.github.io/scihub-manuscript-es/#traductores?

For now we could just create another field in the YAML for `contributors` below authors if we have this situation. Then I can deal with making it show up in the manuscript later.

**Comment by dhimmel** [comment]
> Please have a look at : https://jats4r.org/credit-taxonomy:
it would be best to define exactly what is under the role, url seem prefered to the PID ?

I like the URLs for their human-readability and the ability to be resolved in a web browser, but the URLs like https://dictionary.casrai.org/Contributor_Roles/Visualization return "Oops! That page can’t be found."

I was thinking we could just put `- CREDIT_00000013 writing original draft role` for now and then we can convert this to a different format (or ignore everything but the ID) when we decide how we want to process this and include it in manuscript.

**Comment by mellybelly** [comment]
This is why we created this resolvable version in OWL: https://github.com/data2health/credit-ontology
see also http://obofoundry.org/ontology/cro.html
which imports the original CREDIT terms. 

(note that some of the original terms are a bit conflated, so this is a bit of a problem)

**Comment by mellybelly** [comment]
@dhimmel @cgreene  it would be terrific if manubot could try to implement the CAM model and CRO :-)

**Comment by cgreene** [comment]
I think I tweeted in the past that I would love to see author contributions on mouseover (or similar) in author lists.

**Comment by jcolomb** [comment]
concerning contributor role description, I would take these actions :
- get the cd2h group to define the best way to mention contribution in publication metadata (get a PID of CRO content?), make sure it is compatible with what people did so far.
- make the jats4r change their recommendation accordingly
- implement a yaml version of this
- define manubot output from the yaml

Make sense ?
(PS: I moved question about contributor role in #8)

**Comment by jcolomb** [comment]
this is what I can get out of my program fetching orcid info:
(I started with xml export, so the names of the categories are different, can we work with this?)

```
name:
  given-names: Julien
  surname: Colomb
contrib-id: 0000-0001-9799-2656
github-handle: https://github.com/jcolomb
twitter-handle: []
author-notes:
  email: julien.colomb@fu-berlin.de
affiliation:
- Humboldt-Universität zu Berlin, SFB1315, Institut für Biologie, Charitéplatz 1,
  10117 Berlin
- Friedrich-Schiller-Universität Jena, Informatik  (RDM helpdesk)
role:
- Conceptualization
- Software
funders:
- 'funded by the German Research Foundation, grant_number 327654276: SFB 1315:             Mechanisms
  and disturbances in memory consolidation: From synapses to systems'
- 'funded by the Swiss National Science Foundation, grant_number grant.116951: Memory
  phases of reward learning in Drosophila melanogaster'
.attrs:
  contrib-type: author
  corresponding-author: no
```
