### ISSUE TITLE
contribution attributs

### ISSUE THREAD

**Issue by jcolomb** [data2health/contributorship#8]
Adding contributors who are not authors:

1. categories of contribution beside authors

There is no list or reserved vocabulary for this (yet), jats just gives some examples:
https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/contrib-type.html

2. yaml implementation

```
-  name: Nicole Vasilevsky
    ...
    is_author: yes
    is_corresponding_author: no
```

OR

```
-  name: Nicole Vasilevsky
    ...
    contributor-type: author, translator, research-assistant, editor, ...
    is_corresponding_author: no
```

3. manubot output

in the xml: using contrib-type attibute like jats4r recommendation, or using a <role> entry (easier to implement, may make more sense)

(previously posted in #5 )

**Comment by jcolomb** [comment]
any way to add contributors who are not authors something like
Do you want the translators to show up on the manuscript, like we did for translators at https://greenelab.github.io/scihub-manuscript-es/#traductores?

For now we could just create another field in the YAML for contributors below authors if we have this situation. Then I can deal with making it show up in the manuscript later.

Originally posted by @dhimmel in #5 (comment)

**Comment by dhimmel** [comment]
For [this manuscript](https://data2health.github.io/contributorship/), do we have contributors who are not authors? The easiest solution is often just to write an acknowledgements section like [this example](https://github.com/greenelab/scihub-manuscript/blob/fd9351c2752b1e97b2f55fdfad60a5ec8e10805d/content/90.back-matter.md). I see the appeal of putting non-contributing authors into metadata.yaml for the best structured metadata, although I'd say we should hold off spending a lot of time on this until we actually need it.

To not hold things up, I'd do the following for now if we have non-contributing authors:

```yaml
authors:
  - name: Nicole Vasilevsky
    orcid: 0000-0001-5208-3432
  - name: Barbara Kern
    orcid: 0000-0002-1184-911X
contributors:
  - name: Some contributor
    orcid: XXXX-XXXX-XXXX-XXX
translators:  # Not relevant for this manuscript
  - name: Some translator
    orcid: XXXX-XXXX-XXXX-XXX
```

I don't think this is the best long term solution, but should be sufficient for this manuscript. I am interested in better longterm solutions that we could implement as part of https://github.com/manubot/manubot/issues/187.
